import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { OfflineDetector } from "@/components/ui/offline-detector";
import { GoogleAnalytics } from "@/components/analytics/GoogleAnalytics";
import { AuthProvider } from "@/components/auth/AuthProvider";
import { StoreProvider } from "@/store/StoreProvider";
import { VirtualInputPanel } from "@/components/ui/virtual-input-panel";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <AuthProvider>
            <OfflineDetector />
            {/* Google Analytics - Replace with your Measurement ID */}
            <GoogleAnalytics measurementId="G-XXXXXXXXXX" />
            {children}
            <VirtualInputPanel />
          </AuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
